name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          # Lint your API using Postman CLI
          postman api lint 8ae07b61-c063-4670-b455-17e6ab06d161 --integration-id 168999
          postman collection run "${{ github.workspace }}/postman/collections/Cat Facts.json" --integration-id "168999-${{ github.run_id }}"
         
