name: Publish to Private API Network

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Get API Version from spec
        id: parse-api-version
        uses: mikefarah/yq@master
        with:
          cmd: yq '.info.version' "${{ github.workspace }}/postman/schemas/index.yaml"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: echo ${{ steps.parse-api-version.outputs.result }}
